### ISSUE TITLE
Mario 64 Support?

### ISSUE THREAD

**Issue by naivelychee** [bkacjios/m-overlay#35]
Hello, 
not sure if its possible but I'd love if you could support the  Wii VC version of Mario 64
Thanks!

**Comment by bkacjios** [comment]
The virtual console games don't seem to have the normal game header in memory, making it hard to distinguish what game is currently being ran.

**Comment by little512** [comment]
I've done a bit of research pertaining to Super Mario 64 support, and I've got some code which, indeed, reads my inputs, however, I cannot get the VC version to actually want to use my Gamecube controller to play the game so I can't verify whether or not this method works.

The method is simple:
* The GameID of VC games are stored at `0x80003180` instead of `0x80000000` and are 4 bytes long instead of 6.
* The controller is generic and the struct is stored at address `0x809F38DC`
* The Super Mario 64 GameID is "NAAE", so detect when the loaded VC GameID (the ID at 0x3180) is NAAE and read the gamepad at `0x809F38DC`.

I will continue working on a good method for detecting whether or not the game is a VC game or a regular game, since I do not believe that every Gamecube/Wii title will have consistent 0's (i.e. GAME_NONE) at the GameID address to indicate it's not a VC game.
