### ISSUE TITLE
Does not correctly auto detect port, can not cycle though music with Dpad Down

### ISSUE THREAD

**Issue by CinnaminionTGM** [bkacjios/m-overlay#46]
title says all. setting are Rollback/Netplay and Loop Stage on with D_DOWN set as the control to cycle through music.
when entering games sometimes i see my opponents inputs and the overlay wont let me see my own. when i can see my opponents inputs i cant use dpad down to cycle thru music

**Comment by bkacjios** [comment]
I've heard a few reports of this issue before. I'm not sure why this happens, and I've never been able to reproduce it.

The music skip button will only work for whatever controller is being displayed, which is why it won't work when showing your opponents inputs, because basically, if they press dpad down it will skip.

You can always change the the port yourself, if you ever notice this happening, with the scroll wheel or number pad.

If you can provide the output of the debug console when this issue happens I would appreciate it.

**Comment by CinnaminionTGM** [comment]
Will do!! Ever since I correctly set it manually (left auto detect on) it hasn't been an issue tho.

**Comment by bkacjios** [comment]
I recently fixed a bug where auto detect port would switch to the wrong port when using any other port other than 1 for your local player input.

**Comment by bkacjios** [comment]
I also fixed yet another bug with auto detect port in 1.6.5.
