### ISSUE TITLE
Add support for looping WAV files?

### ISSUE THREAD

**Issue by CinnaminionTGM** [bkacjios/m-overlay#48]
Hi! Would it be possible for m-overlay to recognize and utilize loop points embedded in WAV files?
If added, it would allow for any song to be looped seamlessly and truly replicate the experience of offline Melee's music without butchering the beginnings of songs. Wavosaur is an application that can embed loop points into WAVs, allowing music to loop seamlessly. Winamp and VLC with plugins can recognize the embedded loop points and play WAV looping WAV files. Some game engines [like Source](https://developer.valvesoftware.com/wiki/Looping_a_Sound) detect embedded loop points and loop background music this way.

Here's an example WAV with embedded loops of the music that plays on the Clock Tower stage from MvC2:
[ClockTowerStage.zip](https://github.com/bkacjios/m-overlay/files/5320977/ClockTowerStage.zip)

Some information/documentation on Wavosaur and embedded WAV markers:
https://www.wavosaur.com/quick-help/loop-points-edition.php

**Comment by CinnaminionTGM** [comment]
BTW BRSTM files are actually WAV files with a bunch of different embedded markers. Its possible to convert BRSTM files into looping WAV files. I have done BRSTM -> WAV conversions alot when modding music into Slap City and have a ton more examples if you would like me to upload them (they are large files tho). After converting them into looping WAVs I converted them into FMOD audio files (.snd.fsb) so that I could inject them into Unity

**Comment by CinnaminionTGM** [comment]
(Right now m-overlay recognizes and plays the WAV files fine, but does not recognize the embedded loop markers)

**Comment by CinnaminionTGM** [comment]
Not sure if this helps, but I came across some other software like wavosaur that can add markers to WAV files for loops. It uses the [RtAudio library](http://www.music.mcgill.ca/~gary/rtaudio/), so maybe that could be of some help?

http://loopauditioneer.sourceforge.net/

**Comment by bkacjios** [comment]
So after a bit of research on how to parse a wav file for the loop data and whatnot, I think I finally got something working.. It's not perfect, and a little hacky, but this should allow one loop marker to work.

**Comment by CinnaminionTGM** [comment]
> So after a bit of research on how to parse a wav file for the loop data and whatnot, I think I finally got something working.. It's not perfect, and a little hacky, but this should allow one loop marker to work.

dope!!! im excited :3

**Comment by bkacjios** [comment]
Sorry for the delay on getting this out, but the experimental support for wav loop points was added in 1.7
https://github.com/bkacjios/m-overlay/releases/tag/v1.7

* Music player will now attempt to load and use the loop points inside of WAV files
    - For now, only the first loop point will be used
    - If the song progresses past `sample_end`, it will try to seek to `sample_start`

**Comment by Carldacious** [comment]
I have been experimenting with this, using the WAV file that CinnaminionTGM provided above (ClockTowerStage), and I am not having any luck getting the loop to work correctly on the latest version of m-overlay (1.7). I confirmed in Wavosaur that the markers were present. m-overlay just restarts playback from the beginning when the file ends.

I wanted to ask if this feature could be implemented differently, so that it would not be limited to WAV files. Could you use "LOOP_START" and "LOOP_END" in a file's metadata to inform/activate the loop point? The value in each field would be the number of the sample in the file where it (the loop start or end) occurs.

You could add this information to virtually any audio file using mp3tag: https://www.mp3tag.de/en/download.html
Note: You need to manually add the fields "LOOP_START" and "LOOP_END", as they are not in mp3tag by default.

If you wanted to test your loop using this method, you would need foobar2000 and the vgmstream plugin:
Foobar: https://www.foobar2000.org/download
vgmstream: https://www.foobar2000.org/components/view/foo_input_vgmstream

In preferences in Foobar, make sure under the vgmstream component that 'Loop Forever' is checked. Then, temporarily change the file's extension to have an "l" in front of it. For example, 'flac' becomes 'lflac' or 'ogg' becomes 'logg'. Here is a file for testing:

[FD-logg.zip](https://github.com/bkacjios/m-overlay/files/6170683/FD-logg.zip)
