### ISSUE TITLE
Temporary music mute option

### ISSUE THREAD

**Issue by CinnaminionTGM** [bkacjios/m-overlay#99]
would it be possible to add a temp mute option that is bindable to a controller input?
i really like having music but it can get annoying to close and reopen moverlay sometimes when i want to focus
maybe if you pressed dpad left it could mute/stop the currently playing music, then turn it back on when dpad left or the shuffle button is pressed again?

ps looping wav support looks great and i made a music pack for it!!
https://docs.google.com/document/d/14ZwQjzYIIT3ZmxbQAnKfge8WA2_Bjj01XtcdFON1XUw/edit?usp=sharing
tysm 4 adding that!

**Comment by bkacjios** [comment]
I'll look into it. If we start wanting more settings like this I'm going to have to overhaul the settings menu since we're running out of space.

And, just so you know, the latest builds support Beyond Melee stage music as well.

Also, this link will always be the latest installer, could be worth putting it in your guide, since it will never be outdated: https://github.com/bkacjios/m-overlay/releases/latest/download/m-overlay-x64-installer.exe

**Comment by Carldacious** [comment]
Great work Cinnaminon! I am checking out your work! It's funny, I have been in the process of updating my old pack to incorporate WAV loop points, but with what you've done, I may not need to!

Here's my old pack for reference: https://old.reddit.com/r/SSBM/comments/i2z6xo/melee_music_for_slippi_online_using_moverlay/

Thanks so much bkacjios for making all this possible! It's amazing!

**Comment by bkacjios** [comment]
Added a toggle mute, bindable option in latest release.
